# Use an official Node.js runtime as a parent image
FROM node:21.6.1

# Set the working directory
WORKDIR /usr/project

# Install vim
RUN apt-get update && apt-get install -y vim

# Copy package.json and package-lock.json into /src
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code into /src
COPY . .

# Expose the port the app runs on
EXPOSE 3000
# Transpile the code using Babel
# Define the command to run the app
CMD ["node", "src/App.js"]

